### ISSUE TITLE
Website home

### ISSUE THREAD

**Issue by wps13** [jameswlane/react-pure-loaders#517]
I have tried to access the link given in the repository desciption and found the following: 

![Screen Shot 2019-06-13 at 16 31 39](https://user-images.githubusercontent.com/19312323/59462044-2ba33480-8df9-11e9-9f7c-e38fc6277767.png)

Is the page supposed to look like this? Do you have any plans to change?

**Comment by jameswlane** [comment]
@wps13 Strange the website should be a storybook site with working examples. I am not sure what has happened to it. I will dig into this hopefully this weekend.

**Comment by jameswlane** [comment]
@wps13 I haven’t had time to look at this item. I had knee surgery last Wednesday and was hoping to be able to sit down and dig into this during the weekend. I haven’t been able to. I also would like to add in what you have done for the examples to help people. So I am labeling this “Help Wanted” opening it up to anyone, till I can get to it. If you have time and want to look into it, I would greatly appreciate it.

**Comment by jameswlane** [comment]
Looking into the server logs it looks like it’s missing `babel-loader` from it’s dependencies.

I must of missed something from the Storybook [migration guide](https://github.com/storybookjs/storybook/blob/master/MIGRATION.md) I am not near my laptop at the moment to be able to pull this down and double check the dependencies and that I didn’t miss anything else from the migration.

**Comment by wps13** [comment]
@jameswlane I hope that you get well soon! I will check it.

**Comment by jameswlane** [comment]
@wps13 I appreciate it, hopefully they will get the stitches out this week 🤷‍♂
