### ISSUE TITLE
Domain for the project

### ISSUE THREAD

**Issue by wps13** [jameswlane/react-pure-loaders#540]
Hello, James. I saw your comment about getting a domain for the project. I think that would be nice, cause it would be better for sharing info about the library.

**Comment by jameswlane** [comment]
@wps13 Any suggestions? I was thinking a `react-pure-loaders.io`. But I am open to anything. For example my library `jest-express` domain is `https://jest.express`

**Comment by wps13** [comment]
How about `reactpureloaders.io` ? I think that not using dash would be easier to remember.

**Comment by jameswlane** [comment]
I like it. I will pick it up, and get it added.

**Comment by jameswlane** [comment]
Should have DNS and it linked with Zeit Cloud by tonight.

**Comment by wps13** [comment]
That's great!
