### ISSUE TITLE
Homepage or Landing Page

### ISSUE THREAD

**Issue by jameswlane** [jameswlane/react-pure-loaders#541]
Add a homepage or landing page for the base of the site.
Maybe using the README.md.

**Comment by jameswlane** [comment]
While thinking about it I would be willing to replace Storybook.js as the homepage and make it something like `demo.reactpureloaders.io` and use something simple like `Gatsby.js` as the homepage or something like it.

CC: @wps13 what are your thoughts on this?

**Comment by wps13** [comment]
I was thinking someting similar. For the homepage it would be better using a similar construction for readme, but changing the way as the usage example is showed. For instance:

Import the desired component

```
import { BallBeat } from 'react-pure-loaders';
```
Create the component:

``` 
<BallBeat loading color={'#fff'} />
```
And we could a sort of tutorial, showing the usage.

**Comment by wps13** [comment]
I was thinking that we could improve the documentation, explaining how a component is created

**Comment by jameswlane** [comment]
I like that 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wps13** [comment]
@jameswlane did you start working on the homepage? How can I help you?

**Comment by jameswlane** [comment]
@wps13 I have not yet, I was looking at knocking out a logo first. I am open to any help you would like to do on anything. If you wanna start with the homepage your help is always welcome.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wps13** [comment]
@jameswlane okay, I will start working on it.

**Comment by jameswlane** [comment]
@wps13 You are awesome, I really do appreciate you helping with this project. It's hard being a sole maintainer, having your help with things is making it a lot easier.

**Comment by jameswlane** [comment]
@wps13 would you like a separate repo to host the homepage or would you like to have it stored in the same repo as the project?

**Comment by wps13** [comment]
@jameswlane Thanks! I'm enjoying a lot working with a library, i'm glad that i can help. For the repository, it would be better if it is a separated one, cause it will be easier to do maintenance and would be more organised.

**Comment by jameswlane** [comment]
I think so also, I will make one and give you access to it also.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jameswlane** [comment]
@wps13  here you go: 
https://github.com/jameswlane/reactpureloaders.io

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wps13** [comment]
Thanks!

**Comment by wps13** [comment]
Hello @jameswlane , How you doing? I've been working on the homepage a little bit these days and I wanted to ask about a few details. 

First, about the content direction, which one do you prefer? 

Column | Row
-- | --
![screenshot-localhost-8080-2019 06 29-17-25-41](https://user-images.githubusercontent.com/19312323/60389195-e71fc600-9a93-11e9-831a-d427e1c6400c.png) | ![screenshot-localhost-8080-2019 06 29-17-25-18](https://user-images.githubusercontent.com/19312323/60389196-e8e98980-9a93-11e9-8a73-3f631ea94ae2.png)

For the header, I think that we could add a background color, related to the logo and add the logo itself replacing the logo text. I'm working on both desktop and mobile versions, but still have to fix the getting started section, cause I have problem with the jsx inside the markdown, so I'm looking for a work around and used a image to illustrate how it was supposed to be.

**Comment by jameswlane** [comment]
@wps13 I been well, I am recovered from my surgery so that's a plus. I hope all has been well down your direction? The homepage is looking awesome! I like the column direction better, for me it's easier to read. If you want JSX inside markdown look at [MDX](https://mdxjs.com/). The designer is working on the logo, hopefully will have something by Monday. If you need any help with anything please let me know.

**Comment by wps13** [comment]
@jameswlane Glad to hear that you're recovering well! I'm happy that you liked, I will take a look at mdx. Thanks.

**Comment by jameswlane** [comment]
@wps13 Logo's are done and located [here](https://github.com/jameswlane/react-pure-loaders-logo) for now.

**Comment by wps13** [comment]
@jameswlane great, thanks! Until the weekend I will add them to the site.Also still couldn't fix the mardown issue, mdx didn't work properly with webpack.

**Comment by jameswlane** [comment]
New website is live thanks to @wps13
