### ISSUE TITLE
Logo / Branding?

### ISSUE THREAD

**Issue by jameswlane** [jameswlane/react-pure-loaders#542]
I have had logos made for some of my projects like [Status Board](https://github.com/status-board/logo).
Should I have someone design one for React Pure Loaders? 
If I had Sticker Mule print stickers would you sport it on your laptop?
Or forget branding it, not worth the time?

**Comment by wps13** [comment]
Having a logo would be something nice, but how about the cost?

**Comment by jameswlane** [comment]
I normally get something off Fiverr, normally pay like $25 and get it in three days.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wps13** [comment]
Wow, that's cheaper that I thought.

**Comment by jameswlane** [comment]
The logo for status board is from Fiverr

**Comment by jameswlane** [comment]
@wps13 I started the process to get a logo designed from Fiverr.
I picked a premium package design due to I like to pay the most they are asking for generally.
We get with the premium package:
* 1 Day Delivery
* Unlimited Revisions
* 4 Initial Concepts Included
* Logo Transparency
* Vector File
* Source File
* High Resolution
* 3D Mockup
* Social Media Kit

Is there a way to touch base with you on the designs off GitHub, I don't want to post the raw concept designed on this thread due to the designer owns the copyrights to them and we only get the copyrights to the one we pick.

**Comment by jameswlane** [comment]
@wps13 Logo's are done and located [here](https://github.com/jameswlane/react-pure-loaders-logo).
