### ISSUE TITLE
Move @emotion/core to Peer Dependencies

### ISSUE THREAD

**Issue by jameswlane** [jameswlane/react-pure-loaders#615]

**Comment by Larissagilliane** [comment]
i already did the change and don't see any trouble or  broken feature.

**Comment by jameswlane** [comment]
@Larissagilliane I will be digging into this today.

**Comment by jameswlane** [comment]
@Larissagilliane Thank you for your contributions to the project. I really appreciate all the work you put into your three PR’s. If you can get those issues resolved I will get them merged in as soon as possible.

**Comment by OnkelTem** [comment]
So basically, out of the box it's not gonna work. You have to find this issue, learn about peerDependencies, then install that `@emotion/core` manually. Is my understanding correct?
I just wonder - what is so special about that `@emotion/core` thing that we have to deal with all this? Couldn't it just be added as a regular dependency?

**Comment by jameswlane** [comment]
@OnkelTem We moved it as a peerDependencie to prevent version conflicts of emotion, this allows the end user to maintain and use whatever version of emotion they would like.

The [install instructions](https://github.com/jameswlane/react-pure-loaders#installation) clearly show you need to install not only `react-pure-loaders` but also `@emotion/core`
